FROM fluent/fluentd:v1.14-1

USER root

# Встановлюємо Ruby 3.1 через RVM для сумісності з плагіном
RUN apt-get update && \
    apt-get install -y curl gnupg build-essential && \
    curl -sSL https://rvm.io/mpapis.asc | gpg --import - && \
    curl -sSL https://get.rvm.io | bash -s stable && \
    /bin/bash -l -c "rvm install 3.1 && rvm use 3.1 --default && gem install fluent-plugin-elasticsearch -v 5.0.3 --no-document"

USER fluent
