version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./log:/fluentd/log
    depends_on:
      - fluentd

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    volumes:
      - ./log:/fluentd/log
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
